### ISSUE TITLE
Link to gitmirror in README.md

### ISSUE THREAD

**Issue by Mx-Glitter** [dav-m85/busfactor#2]
The link to [gitmirror](https://github.com/lafourchette/gitmirror) [here](https://github.com/dav-m85/busfactor/blob/master/README.md#related) does not seem to be relevant. Is it possible to explicit why the link is here, or to remove it if it's not needed anymore?

**Comment by dav-m85** [comment]
I made it more clear. However, I shall remove this at then end and bundle all the major common classes separately.
