### ISSUE TITLE
Report legend is misleading

### ISSUE THREAD

**Issue by Mx-Glitter** [dav-m85/busfactor#4]
Report legend indicates that red is for when busfactor is low (0% to lower_threshold), and green for high busfactor (higher_threshold to 100%), whereas it's inverted in the report (see [README.md screenshot](https://raw.githubusercontent.com/dav-m85/busfactor/master/doc/screenshot.png) for an example)

IMHO to be consistent, red should be for danger, when the busfactor is very high, so legend shoud be updated.

**Comment by dav-m85** [comment]
That's because of the BF definition : percentage of file having only one hero commiter. Hence 100% = all your files got only one commiter = danger.

Maybe I should change the definition to "number of files that got more than one commiter". Then 0% = danger.

**Comment by Mx-Glitter** [comment]
I'm not sure I stated what's confusing me correctly. I find it strange on the legend to see that red is for 0% to 10% for example and see in the report red for 100% for packageRepository.js on the [README.md screenshot](https://raw.githubusercontent.com/dav-m85/busfactor/master/doc/screenshot.png).
